name: Code quality checks
run-name: Quality checks on branch ${{ github.head_ref }}

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run type check
        run: yarn type:check
